manifest:
  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.3.1
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-zephyr.yml
        path-prefix: deps
        name-allowlist:
          - zephyr
          - cmsis
          - hal_espressif
          - mbedtls
          - mcuboot
          - net-tools
          - qcbor
          - segger
          - tinycrypt
  self:
    path: app
