manifest:
  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: 7f2f55e386c4cef588ecf8d8cf5305ffe73615e3
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-zephyr.yml
        path-prefix: deps
        name-allowlist:
          - zephyr
          - cmsis
          - hal_espressif
          - mbedtls
          - mcuboot
          - net-tools
          - qcbor
          - segger
          - tinycrypt
  self:
    path: app
    west-commands: utility/west-commands/west-commands.yml
